name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get version from system.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' system.json)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Create Git Tag
        run: |
          git tag v${{ env.version }}
          git push origin v${{ env.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./newFVTTRPG.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
